name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "::set-env name=NOW::$(date +'%Y%m%d.%H%M%S')"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install muslc
        run: sudo apt-get update && sudo apt-get install -y musl-tools gcc-mingw-w64-x86-64
      - name: Run Linux build
        env:
          HIDEKEY: ${{ secrets.HIDEKEY }}
        run: make all CC=musl-gcc 
      - name: Run Windows (Mingw) build
        env:
          HIDEKEY: ${{ secrets.HIDEKEY }}
        run: make all CC=x86_64-w64-mingw32-gcc-win32 CCEXTRA='-lws2_32'
      - uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: out/*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          files: out/*
          name: "latest"
          tag_name: "${{ env.NOW }}"
          make_latest: true
