name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install muslc
        run: sudo apt-get update && sudo apt-get install -y musl-tools
      - name: Run build
        env:
          HIDEKEY: ${{ secrets.HIDEKEY }}
        run: make all CC=musl-gcc 
      - uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: out/*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: out/*